# Generated by Django 5.2.3 on 2025-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='contenido',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
