# Generated by Django 5.2.3 on 2025-07-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0002_remove_documento_contenido_documento_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estadistica',
        ),
    ]
