# Generated by Django 5.2.3 on 2025-07-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0002_remove_documento_contenido_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='reserva',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibo', to='camara.reserva'),
        ),
    ]
