# Generated by Django 5.2.3 on 2025-07-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0003_alter_recibo_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='enlace',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace externo'),
        ),
    ]
