from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('registro/', views.registro, name='registro'),
    path('registro-empresa/', views.registro_empresa, name='registro_empresa'),
    path('afiliacion/', views.afiliacion, name='afiliacion'),
    path('convenios/', views.convenios, name='convenios'),
    path('faq/', views.faq, name='faq'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
    path('historial-reservas/', views.historial_reservas, name='historial_reservas'),
    path('notificaciones/', views.notificaciones, name='notificaciones'),
    path('logout/', views.logout_view, name='logout'),  # Añadido aquí
    path('admin-home/', views.admin_home, name='admin_home'),
    path('afiliaciones-pendientes/', views.afiliaciones_pendientes, name='afiliaciones_pendientes'),
    path('afiliacion/<int:pk>/', views.detalle_afiliacion, name='detalle_afiliacion'),
    path('admin-convenios/', views.admin_convenios_list, name='admin_convenios_list'),
    path('admin-convenios/crear/', views.admin_convenio_create, name='admin_convenio_create'),
    path('admin-convenios/<int:pk>/editar/', views.admin_convenio_edit, name='admin_convenio_edit'),
    path('admin-convenios/<int:pk>/eliminar/', views.admin_convenio_delete, name='admin_convenio_delete'),
    path('aprobar-usuario/<int:user_id>/', views.aprobar_usuario, name='aprobar_usuario'),
    path('cambio-obligatorio-contrasena/', views.cambio_obligatorio_contrasena, name='cambio_obligatorio_contrasena'),
    path('admin-servicios/', views.admin_servicios_list, name='admin_servicios_list'),
    path('admin-servicios/crear/', views.admin_servicio_create, name='admin_servicio_create'),
    path('admin-servicios/<int:pk>/editar/', views.admin_servicio_edit, name='admin_servicio_edit'),
    path('admin-servicios/<int:pk>/eliminar/', views.admin_servicio_delete, name='admin_servicio_delete'),
    path('servicios/', views.servicios_publicos, name='servicios_publicos'),
    path('servicios/<int:pk>/reservar/', views.reservar_servicio, name='reservar_servicio'),
    path('solicitar-seguro-vida/', views.solicitar_seguro_vida, name='solicitar_seguro_vida'),
    path('admin-notificacion/', views.admin_notificacion, name='admin_notificacion'),
    path('admin-convenios/<int:convenio_id>/beneficio/', views.admin_beneficio_create, name='admin_beneficio_create'),
    path('admin-reservas/', views.admin_reservas_list, name='admin_reservas_list'),
    path('admin-reservas/<int:pk>/cambiar-estado/', views.admin_reserva_estado, name='admin_reserva_estado'),
    path('reservas/<int:pk>/generar-recibo/', views.generar_recibo, name='generar_recibo'),
    path('recibo/<int:pk>/', views.ver_recibo, name='ver_recibo'),
    path('admin-ver-afiliados/', views.admin_ver_afiliados, name='admin_ver_afiliados'),
]
